# Specify version format
version: "0.1.{build}"

# Operating system (build VM template)
os: Previous Visual Studio 2015
#Visual Studio 2013 #older version

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  # - Win32 Disable Win32
  - x64
  
# specify custom environment variables
environment:
  # - BOOST_DIR: C:\Libraries\boost_1_59_0
  BOOST_DIR: C:\Libraries\boost_1_60_0


# build configuration, i.e. Debug, Release, etc.
configuration:
 # - Release
  - BoostTest

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\FLAMEGPU2_dev

# scripts that run after cloning repository (requires reboot to propagate installer env variables)
install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64  #installing vc++
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64 #installing vc++
  - ps: .\scripts\appveyor_install.ps1
  - ps: Write-Output 'Rebooting worker node...'
  - ps: sleep 5
  - ps: restart-computer -f
  - ps: sleep 5
  - ps: Write-Output 'Reboot complete'
  - ps: (Get-Content -Path "C:\projects\FLAMEGPU2_dev\FLAMEGPU2.vcxproj") | ForEach-Object {$_ -Replace "9.1", "8.0"} | Set-Content -Encoding UTF8 -Path C:\projects\FLAMEGPU2_dev\FLAMEGPU2.vcxproj
  #- ps: (Get-Content "C:\projects\FLAMEGPU2_dev\FLAMEGPU2.vcxproj") -replace '9.1', '8.0' | Out-File C:\projects\FLAMEGPU2_dev\FLAMEGPU2.vcxproj
# make sure nvcc is working correctly
  #- cmd: nvcc -V

# The build
build:
  project: C:\projects\FLAMEGPU2_dev\FLAMEGPU2.sln # path to Visual Studio solution or project

#debugging
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
